(function(e){var s=function(a,c){var f={0:"",1:"",2:"<span>\u63a5\u53e3\u5f02\u5e38</span>",3:"<span>\u6570\u636e\u52a0\u8f7d\u5b8c\u6210</span>",4:"<span>\u914d\u7f6e\u4e0d\u5b8c\u5584</span>"};return function(g){c&&console&&console.log(g);1==g?e(a).removeClass("top").addClass("bottom").show():2==g?e(a).html(f[g]):3==g?e(a).html(f[g]).show():4==g?e(a).html(f[g]).show():a.hide()}},t=function(a,c,f){function g(m){null==d&&!1==h?(b.debug&&console&&console.log("\u8fd8\u6ca1\u6709resize \u8bbe\u7f6esetimeout"),
d=setTimeout(function(){l(m)},500)):null!=d&&!1==h?(b.debug&&console&&console.log("\u5c06\u8981resize"),clearTimeout(d),d=setTimeout(function(){l(m)},500)):null!=d&&!0==h&&(b.debug&&console&&console.log("\u6b63\u5728resize"),d=setTimeout(function(){l(m)},500))}function l(m){b.debug&&console&&console.log("start resize..");h=!0;var a=c.width();b.debug&&console&&console.log("new width "+a);var f={};a>b.min_width&&(f.cols=Math.floor(a/b.width),f.colspan=Math.floor((a-f.cols*b.width)/(f.cols-1)),b.debug&&
console&&console.log(f),b=e.extend(b,f),b.debug&&console&&console.dir(b),m.reflow());h=!1;d=null}var k,b,h=!1,d=null;b=e.extend({cols:2,colspan:10,width:230,debug:!1,backtotop:"#BackToTop",notice:"#loadingPins"},a);(function(b){k=c.width();b.debug&&console&&console.log("width"+k);b.min_width=b.col*(b.width+10);b.debug&&console&&console.log("\u6700\u5c0f\u5bbd\u5ea6 "+b.min_width);k>b.min_width&&(b.cols=Math.floor(k/b.width),b.colspan=Math.floor((k-b.cols*b.width)/(b.cols-1)));e(b.notice).show();return b})(b);
b.debug&&console&&console.dir(b);b.debug&&console&&console.log("\u5b9e\u9645\u5217 "+b.cols);b.debug&&console&&console.log("\u5b9e\u9645\u5217\u95f4\u8ddd "+b.colspan);var q={start:function(){var a=this;e(window).bind("scroll",function(){var g=e(window).scrollTop();b.debug&&console&&console.log("scroll top:"+g);var d=c.height();b.debug&&console&&console.log("exper height:"+d);var n=e(window).height();b.debug&&console&&console.log("window height:"+n);20>d-(g+n)&&(b.debug&&console&&console.log("i am here "),
f(1),b.getImageData(p),a.pause())})},pause:function(){e(window).unbind("scroll")}},r=new function(){var a=[];(function(){for(var c=0;c<b.cols;c++)a[c]=0})();b.debug&&console&&console.log("init array"+a);var f=function(){for(var c=0,e=0;e<b.cols;e++)a[e]<a[c]&&(c=e);return c},g=function(){for(var c=0,e=0;e<b.cols;e++)a[e]>c&&(c=a[e]);return c+46};return{readyImage:function(d){d&&(e.each(d,function(e,d){d.col=f();d.top=a[d.col];d.left=d.col*(b.width+b.colspan);d.height=d.img_height+42;d.data_col="data_col_"+
d.col;d.data_id="data_"+d.top+d.left;var h=d.height;a[d.col]+=h+30;c.css({height:g()})}),d=b.renderItemHtml(d),c.append(d))},reflow:function(){var d=b.cols,h=b.colspan;b.debug&&console&&console.log("new colspan: "+h);for(h=0;h<d;h++)a[h]=0;c.children().each(function(c,d){var g=e(d),h=g.css("height"),h=h.replace("px",""),h=parseInt(h),k=f(),l=k*(b.width+b.colspan),n=a[k];b.debug&&console&&console.log("id:"+c+" col:"+k+" left: "+l+"top: "+n+" height="+h);g.css({left:l,top:n});g=h+30;a[k]+=g});c.css({height:g()})}}},
p=function(a,c){this.end=function(){b.debug&&console&&console.log("i am ending");q.pause()};c?a?(e(b.notice).hide(),e(b.backtotop).show(),r.readyImage(a),q.start()):(f(2),this.end()):(f(3),this.end())};b.getImageData(p);e(window).resize(function(){g(r)});e(b.backtotop).bind("click",function(){e(b.backtotop).scrollTop(0)})};e.WaterFall=function(a,c,f){e.data(c,"WaterFall",new t(a,c,f));return c};e.fn.WaterFall=function(a){var c;c=!1;"object"!==typeof a&&(a.debug&&console&&console.log("bug in here!"),
c=!0);!a.hasOwnProperty("getImageData")&&(a.hasOwnProperty("col")&&a.hasOwnProperty("width")&&a.hasOwnProperty("colspan"))&&(a.debug&&console&&console.log("bug in here!"),c=!0);"function"!==typeof a.getImageData&&(a.debug&&console&&console.log("bug in here!"),c=!0);if("number"!==typeof a.col||0==a.col)a.debug&&console&&console.log("bug in here!"),c=!0;if("number"!==typeof a.width||0==a.width)a.debug&&console&&console.log("bug in here!"),c=!0;if("number"!==typeof a.colspan||0==a.colspan)a.debug&&console&&
console.log("bug in here!"),c=!0;if("string"!==typeof a.backtotop||!/^\#/.test(a.backtotop))a.debug&&console&&console.log("bug in here!"),c=!0;if("string"!==typeof a.notice||!/^\#/.test(a.notice))a.debug&&console&&console.log("bug in here!"),c=!0;var f=new s(a.notice,a.debug);c?f(4):e.WaterFall(a,this,f)}})(jQuery);
